version: '2.4'
services:

  php:
    image: pimcore/pimcore:PHP7.4-apache
    container_name: pavic-php
    environment:
      - VIRTUAL_HOST=pavic.a22.localhost
    volumes:
      - .:/var/www/html:cached

    networks:
      - docker-proxy_default
      - default

networks:
  docker-proxy_default:
    external: true